### ISSUE TITLE
Data Missing

### ISSUE THREAD

**Issue by AndrewSkelton** [neurogenomics/reanalysis_Mathys_2019#1]
Hi, 

Thanks for the re-analysis of this dataset and making it reproducible - big kudos to you guys for tackling a huge problem in the proliferation of single cell data and best practise lagging behind. 

I wanted to take a look at the data object, but it seems figshare have killed it. I wonder if you can host on Zenodo, which also provides a DOI / versioning of the uploads? 

Thanks, 

Andrew

**Comment by Al-Murphy** [comment]
Hey Andrew,

Apologies not sure how I missed this issue. Unfortunately, we can not make the processed data available through figshare - Initially we thought this would be okay since we are only dealing with aggregated count matrices and not individual level data but after writing the draft of the manuscript (which is up on Biorxiv), we realised this would not be possible as the patients are part of [ROSMAP](https://www.synapse.org/#!Synapse:syn3157322) which does not allow it. Likewise, we are not permitted to share the data privately. We are currently in the process of getting our reprocessed data up on synapse so people can apply for access there however, this is proving very slow. We will update the preprint once this is available though (again, you will still need to apply for access to it).

Alternatively, you could apply for access to the unprocessed data from the original study by Mathys et al. and rerun our preprocessing steps that we discuss in the paper using scFlow. The link is here: https://www.synapse.org/#!Synapse:syn18485175

Apologies that I can't be more helpful at this time, our hands are rather tied.

Alan.

**Comment by Al-Murphy** [comment]
Hi our reprocessed data is now available through Synapse, see: https://doi.org/10.7303/syn51758062.1
